name: SahajaSpringer
favicon: null
layout_spectrum: 0.48671
typography_spectrum: 0.65609
title: Fast Forward Your Vision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aab5b9'
    - '#fefefe'
    - '#3b3738'
    - '#616066'
    - '#a47c5d'
  brandStrength: 0.8170600130688399
  lightness: 0.032403199234977365
  saturation: 0.1708530578762293
  rhythmicContrast: 0.9997185526881367
purpose: []
