name: SahajaSpringer
favicon: null
layout_spectrum: 0.5193032298702747
typography_spectrum: 0.4676710038911551
title: Fast Forward Your Vision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8170600130688399
  lightness: 0.032403199234977365
  saturation: 0.1708530578762293
  rhythmicContrast: 0.9997185526881367
purpose: []
